server:
  host: ${SERVER_HOST}
  port: ${SERVER_PORT}
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
app:
  cache:
    cache-names:
      - booksByTitleAndAuthor
      - booksByCategory
    caches:
      booksByTitleAndAuthor:
        expiry: ${BY_TITLE_AND_AUTHOR_CACHE_EXPIRY}
      booksByCategory:
        expiry: ${BY_CATEGORY_CACHE_EXPIRY}