server:
  host: ${SERVER_HOST}
  port: ${SERVER_PORT}
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      schema: contacts_schema

repository-impl:
  type: ${REPO_IMPL_TYPE}
sample-data:
  enabled: ${SAMPLE_DATA_ENABLED}