version: '3'
services:
  psql:
    image: postgres:15
    ports:
      - 5432:5432
    container_name: psql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=news_service_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  news-service:
    image: news-service
    ports:
      - 8888:8888
    container_name: news-service
    environment:
      - SERVER_HOST=localhost
      - SERVER_PORT=8888
      - DB_HOST=psql
      - DB_PORT=5432
      - DB_NAME=news_service_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - psql
