server:
  host: localhost
  port: 8080

spring:
  jpa:
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/news_service_db
    username: postgres
    password: postgres

app:
  authentication-type: jwt
  jwt:
    secret: "someSecretKey"
    tokenExpiration: 3m
    refreshTokenExpiration: 30m