server:
  host: ${APP_HOST}
  port: ${APP_PORT}

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  jpa:
    generate-ddl: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      schema: newsservice_schema
      connection-timeout: 10000
  profiles:
    active: default

app:
  authentication-type: ${AUTH_TYPE}
  jwt:
    secret: ${JWT_SECRET}
    tokenExpiration: ${JWT_ACCESS_EXPIRATION}
    refreshTokenExpiration: ${JWT_REFRESH_EXPIRATION}